### ISSUE TITLE
Iteration Plan of v0.22.0 - December 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#1071]
This plan captures our work in December 2021. 
We will support multiview 3D keypoint detection, and refactor data transforms for flexible usage and scalability.

### Algorithms

- [x] [VoxelPose](https://github.com/microsoft/voxelpose-pytorch) (ECCV'20) @wusize  #1050  
- [ ] [LSTM Pose Machines](https://arxiv.org/abs/1712.06316) (CVPR'18) @luminxu 
- [ ] [HRFormer](https://arxiv.org/pdf/2110.09408.pdf) (NeurIPS'21) @zengwang430521  https://github.com/open-mmlab/mmsegmentation/pull/1112
- [x] [AdaptiveWingLoss](https://arxiv.org/abs/1904.07399) (ICCV'19) @jin-s13  #1072 
- [x] [SoftWingLoss](http://openaccess.thecvf.com/content_cvpr_2014/html/Toshev_DeepPose_Human_Pose_2014_CVPR_paper.html) (TIP'2021) @jin-s13 #1077 

### Datasets

- [x] [CMU Panoptic](https://openaccess.thecvf.com/content_iccv_2015/html/Joo_Panoptic_Studio_A_ICCV_2015_paper.html) (ICCV'15) @wusize  #1050 

### Features

- [ ] Refactor data transforms to support configurable input/output field and apply-to-multiple. @ly015
