### ISSUE TITLE
Iteration Plan of v0.25.0 - March 2022

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#1254]
This is our iteration plan for MMPose v0.25.0

### Algorithms

- [x] [SmoothNet](https://arxiv.org/abs/2112.13715) (arXiv'21) @ailingzengzzz   #1279 
- [ ] [Swin-Pose](https://arxiv.org/abs/2201.07384) (arXiv'22) @yumendecc #1230 

### Datasets

- [x] [Campus and Shelf datasets](http://campar.in.tum.de/pub/belagiannis2014cvpr/belagiannis2014cvpr.pdf) (CVPR'14) @liqikai9 #1225 

### Features

- [x] Add multi-view 3D pose estimation demo @wusize  #1222 
- [x] Add `Smoother` module for temporal smoothing pose results @ailingzengzzz @ly015  #1127 
- [x] Update HRFormer checkpoints @zengwang430521 #1245
