### ISSUE TITLE
Iteration Plan of v0.26.0 - April 2022

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#1303]
This is our iteration plan for MMPose v0.26.0

### Algorithms

- [ ] Support [Residual Log-likelihood Estimation](https://arxiv.org/abs/2107.11291) (ICCV'21, Oral) @Indigo6 #1259 
- [ ] Support [Swin-Pose](https://arxiv.org/abs/2201.07384) (arXiv'22) @yumendecc #1230 
- [ ] Support [PoseFormer](https://arxiv.org/abs/2103.10455) (ICCV'21) @QwQ2000 #1215 
- [ ] Support [Pyramid Vision Transformer](ICCV'21) @zengwang430521 
- [ ] Support [DeciWatch](https://arxiv.org/abs/2203.08713) (arXiv'22) @ailingzengzzz 

### Features

- [ ] Support configurable model initialization @ly015 

### Documents and Demos

- [ ] Add video 2D pose estimation demo @liqikai9
