### ISSUE TITLE
Iteration Plan - Nov 2020

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmpose#231]
It's time to plan for MMPose v0.9. This will be a one-month iteration and our focus in this iteration is to enrich the supported tasks. We will support for 3D hand keypoint estimation & video pose estimation.

Tasks & Datasets:
- [ ] ~~InterHand 3d hand keypoint estimation~~
- [x] JHMDB video pose estimation (#292)

Algorithms:
- [x] MSPN (https://github.com/open-mmlab/mmpose/pull/278)
- [x] RSN (#221)

Misc:
- [ ] ~~Batch inference during test (#297)~~
- [ ] ~~Calculate FLOPS, MAC, Memory~~

---

Deferred:

- [ ] InterHand 3d hand keypoint estimation
- [ ] Batch inference during test (#297)
- [ ] Calculate FLOPS, MAC, Memory
