### ISSUE TITLE
December Iteration Plan

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmpose#337]
Here is the plan for December, and we will release v0.10.0 in the end of the month. Our focus in this iteration is to enrich the supported tasks. We will add support for 2d face keypoint localization.

### Tasks & Datasets

- [ ] ~~Face keypoint localization~~ #367 
    - 300W
    - COFW 
    - AFLW
    - WFLW
- [x] [LV-MHP v2 datasets](https://lv-mhp.github.io/pose_estimation_task) for both top-down and bottom-up approaches https://github.com/open-mmlab/mmpose/pull/386

### Algorithms

- [x] UDP algorithm #291 
- [x] UDP unittest #371
- [x] UDP checkpoints #402 

### Misc

- [ ] ~~Support multi-dataset training~~ #387 
- [ ] ~~Support multi-head models~~ #219 
- [x] Add Pose Tracking demo #380
- [x] Calculate FLOPS, MAC, Memory #324

---

### Deferred

- [ ] Face keypoint localization #367 
    - 300W
    - COFW 
    - AFLW
    - WFLW
- [ ] Support multi-dataset training #387 
- [ ] Support multi-head models #219

**Comment by zgs731** [comment]
When will the video pose estimation be realized?

**Comment by huangzhenjie** [comment]
hello, when i want to use pytorchToonnx, I encountered a small bug, it should be a relative path problem.
![微信截图_20201223112220](https://user-images.githubusercontent.com/13945470/102957317-19897280-4515-11eb-93e2-e5bf5601a249.png)
by the way，I do not how to create a new issue.
![微信截图_20201223114806](https://user-images.githubusercontent.com/13945470/102957248-ee9f1e80-4514-11eb-833a-98e9868212cf.png)

**Comment by jin-s13** [comment]
@zgs731 We have added some video pose estimation datasets (PoseTrack18 and JHMDB datasets), along with some baseline models. Please have a try. Other video pose estimation algorithms are still in progress. You may vote [here](https://github.com/open-mmlab/mmpose/issues/9).

@huangzhenjie   I will create an issue and check this problem
