### ISSUE TITLE
Iteration Plan January

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmpose#408]
Here is the plan for January, and we will release v0.11.0 in the end of the month. Our focus in this iteration is to refactor the code/doc structure and support more tasks.

### Tasks & Datasets

- [x] Face keypoint localization #367 
    - 300W
    - COFW 
    - AFLW
    - WFLW
- [x] Support Fashion Landmark Detection #413
- [x] AIC dataset for bottom-up methods #438

### Algorithms
- [ ] ~~Support regression based model~~ #446 
   - DeepPose 
- [ ] ~~Support ZoomNet~~

### Misc

- [ ] ~~Support multi-dataset training~~ #387 
- [x] Refactor heads and support multi-head models #382
- [ ] ~~Refactor config file structure~~
- [ ] ~~Refactor doc structure~~

---

### Deferred

- Support ZoomNet
- Support multi-dataset training #387 
- Refactor config file structure
- Refactor doc structure
- Support regression based model #446 
   - DeepPose
