### ISSUE TITLE
Iteration Plan February

### ISSUE THREAD

**Issue by jin-s13** [open-mmlab/mmpose#470]
Happy Chinese New Year!
Here is the plan for February, and we will release v0.12.0 in the end of the month. Our focus in this iteration is to support more algorithms.

### Tasks & Datasets
- [x] Support Interhand3d dataset #468
### Algorithms
- [x] Support regression based model #446 
   - DeepPose 
- [ ] ~~Support ZoomNet~~
### Misc
- [x] Support Albumentations #469
- [x] Add README in Chinese #462
- [x] Add tutorials on config #465
- [x] Demos for all supported tasks #499 
- [ ] ~~Speed up inference~~ 
- [ ] ~~Multiple dataset training~~ (removed)
---

### Deffered

- [ ] Support ZoomNet
- [ ] Speed up inference
