### ISSUE TITLE
Iteration Plan March

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmpose#513]
This month, we plan to extend our algorithms to the 3d world!

### Algorithms

- [x] Support [Interhand3d](https://github.com/facebookresearch/InterHand2.6M) model  #480, #536
- [x] A simple yet effective baseline for 3d human pose estimation (ICCV'17) #518, #521, #522, #524, #527

### Misc

- [x] Wingloss #482 
- [x] Data augmentation configs and checkpoints #525 
- [x] Speed up inference #535 

---
