### ISSUE TITLE
Iteration Plan for Apr 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#556]
This plan captures our work in April. We will extend our framework to animal pose estimation 🐭 🐁 🐶 😹 , and support more 2D/3D pose estimation algorithms.

### Tasks
- [x] Support animal pose estimation @jin-s13  #559 
- [ ] Support human 3D pose estimation from videos @ly015 

### Datasets
- [ ] ~~[HumanEva-I](http://humaneva.is.tue.mpg.de/datasets_human_1) dataset~~ @ly015 
- [x] [Horse-10](http://www.mackenziemathislab.org/horse10) dataset @jin-s13
- [x] [MacaquePose](http://www.pri.kyoto-u.ac.jp/datasets/macaquepose/index.html) dataset @jin-s13
- [x] [Vinegar Fly](https://github.com/jgraving/DeepPoseKit-Data) dataset @jin-s13
- [x] [Desert Locust](https://github.com/jgraving/DeepPoseKit-Data) dataset @jin-s13
- [x] [Grévy’s Zebra](https://github.com/jgraving/DeepPoseKit-Data) dataset @jin-s13
- [x] [Animal-Pose](https://sites.google.com/view/animal-pose/) dataset @jin-s13 

### Algorithms
- [ ] ~~[OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19)~~ @luminxu 
- [ ] [3D human pose estimation in video with temporal convolutions and semi-supervised training](https://arxiv.org/abs/1811.11742) (CVPR'19) @cherryjm 
- [ ] ~~[InterHand2.6M: A Dataset and Baseline for 3D Interacting Hand Pose Estimation from a Single RGB Image](https://arxiv.org/abs/2008.09309) (ECCV‘20)~~ @liuxin9608 @zengwang430521 
- [x] [A simple yet effective baseline for 3d human pose estimation](https://arxiv.org/abs/1705.03098) (ICCV‘17) @ly015 
- [ ] ~[PifPaf: Composite Fields for Human Pose Estimation](https://arxiv.org/abs/1903.06593) (CVPR'19) @luminxu~

### Misc
- [ ] ~~Refactor model evaluation based on the MMCV eval hook~~ @ly015 
- [ ] Speed up inference (round 2) @jin-s13 

---

### Deferred

- Refactor model evaluation based on the MMCV eval hook @ly015 
- [OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19) @luminxu 
- [InterHand2.6M: A Dataset and Baseline for 3D Interacting Hand Pose Estimation from a Single RGB Image](https://arxiv.org/abs/2008.09309) (ECCV‘20) @liuxin9608 @zengwang430521 
- [3D human pose estimation in video with temporal convolutions and semi-supervised training](https://arxiv.org/abs/1811.11742) (CVPR'19) @cherryjm
