### ISSUE TITLE
Iteration Plan for May 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#631]
This plan captures our work in May. We will refactor our framework towards conciseness, ease of use, and extensibility. And more 2D/3D pose estimation algorithms will be supported.

### Algorithms

- [ ] ~~[PRTR](https://arxiv.org/abs/2104.06976) (CVPR'21)~~ @ly015 
- [ ] ~~[OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19)~~ @luminxu 
- [x] [InterHand2.6M: A Dataset and Baseline for 3D Interacting Hand Pose Estimation from a Single RGB Image](https://arxiv.org/abs/2008.09309) (ECCV‘20) @liuxin9608 @zengwang430521  #624 
- [x] [3D human pose estimation in video with temporal convolutions and semi-supervised training](https://arxiv.org/abs/1811.11742) (CVPR'19) @cherryjm https://github.com/open-mmlab/mmpose/pull/602

### Refactor
- [x] Reorganize configs by tasks, algorithms, datasets, model settings, and techniques @jin-s13 #647 
- [ ] ~~Streamlining dataset classes~~ @jin-s13  #663 
- [x] Rename heads and detectors @jin-s13  #667 
- [ ] ~~Refactor postprocessing to adopt pipelines and operators and disentangle postprocessing and heads.~~ @ly015 

### Misc
- [ ] ~~Refactor model evaluation based on the MMCV eval hook~~ @ly015 

---

### Deferred

- [ ] Streamlining dataset classes @jin-s13  #663 
- [ ] Refactor postprocessing to adopt pipelines and operators and disentangle postprocessing and heads. @ly015 
- [ ] Refactor model evaluation based on the MMCV eval hook @ly015 
- [ ] [OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19) 
- [ ] [PRTR](https://arxiv.org/abs/2104.06976) (CVPR'21) @ly015
