### ISSUE TITLE
Iteration Plan for June 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#701]
This plan captures our work in June. We will continue focusing on improving the code quality and user experience.

### Algorithms & Datasets
- [ ] ~~[PRTR](https://arxiv.org/abs/2104.06976) (CVPR'21)~~ @ly015 
- [ ] ~~[OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19)~~ @luminxu #651 
- [x] [MPI-INF-3DHP](https://arxiv.org/abs/1611.09813) @cherryjm  #683 

### Refactor
- [ ] ~~Refactor postprocessing to adopt pipelines and operators and disentangle postprocessing and heads~~ @ly015 
- [ ] ~~Refactor model evaluation based on the MMCV eval hook~~ @ly015 #686 
- [ ] ~~Streamlining dataset classes~~ @jin-s13  #663 
- [x] Refactor 3D mesh model towards better flexibility and extensibility @zengwang430521  #752 

### Docs & Demos
- [ ] ~~Add Chinese documents~~ @ly015 @jin-s13 @innerlee 
- [x] Update demos to better present mmpose functions and features @ly015 @jin-s13 #704, #722, #727, #729
- [ ] ~~Add a Colab demo script~~ @ly015 
- [ ]~~ Move useful info to docs from issues with [faq candidate](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22faq+candidate%22), [faq ](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22faq%22), [documentation](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22documentation%22) and [knowledge base](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22knowledge+base%22) labels.~~

### Misc
- [x] Support [mim](https://github.com/open-mmlab/mim) @ly015 @cherryjm #706 #749 

---

### Deferred

Due to lack of hands, some of the items will be deferred to 2021.8.

- [ ] [PRTR](https://arxiv.org/abs/2104.06976) (CVPR'21) @ly015 
- [ ] [OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19) @luminxu 
- [ ] Refactor postprocessing to adopt pipelines and operators and disentangle postprocessing and heads @ly015 
- [ ] Refactor model evaluation based on the MMCV eval hook @ly015 #686 
- [ ] Streamlining dataset classes @jin-s13  #663 
- [ ] Add Chinese documents @ly015 @jin-s13 @innerlee 
- [ ] Add a Colab demo script @ly015 
- [ ]  Move useful info to docs from issues with [faq candidate](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22faq+candidate%22), [faq ](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22faq%22), [documentation](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22documentation%22) and [knowledge base](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22knowledge+base%22) labels.
