### ISSUE TITLE
Iteration Plan for July 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#786]
This plan captures our work in July. We will continue focusing on improving the code quality and user experience.

### Algorithms & Datasets
- [ ] [OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19)  @luminxu @jin-s13 #651
- [x] [LiteHRNet](https://arxiv.org/abs/2104.06403) @jin-s13 #733 

### Refactor
- [ ] Refactor postprocessing to adopt pipelines and operators and disentangle postprocessing and heads @ly015 
- [x] Refactor model evaluation based on the MMCV eval hook @ly015 #686 
- [ ] Streamlining dataset classes @jin-s13  #663 
- [ ] Refactor human 3d parametric model interface @zengwang430521 #830 

### Docs & Demos
- [x] Add Chinese documents @ly015 @jin-s13 @innerlee #787 #772 
- [x] Add a Colab demo script @ly015 #834 
- [x] Add 3D Mesh Demo @zengwang430521  #771 
- [ ] Move useful info to docs from issues with [faq candidate](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22faq+candidate%22), [faq ](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22faq%22), [documentation](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22documentation%22) and [knowledge base](https://github.com/open-mmlab/mmpose/issues?q=+is%3Aissue+label%3A%22knowledge+base%22) labels.
