### ISSUE TITLE
Iteration Plan for August 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#851]
This plan captures our work in August. 

### Algorithms

- [ ] [OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields](https://arxiv.org/abs/1812.08008) (TPAMI'19)  @luminxu @jin-s13 #651
- [ ] [Coarse-to-Fine Volumetric Prediction for Single-Image 3D Human Pose](https://arxiv.org/abs/1611.07828) @ZhiYuan-REN 
- [ ] [Learning to Reconstruct 3D Human Pose and Shape via Model-fitting in the Loop](https://arxiv.org/abs/1909.12828) @zengwang430521 

### Refactors

- [ ] Streamlining dataset classes @jin-s13  #663 
- [ ] Refactor human 3d parametric model interface @zengwang430521 #830 
- [ ] Refactor dataset classes towards unified interface for various tasks @ly015 
- [ ] Refactor postprocessing to adopt pipelines and operators and disentangle postprocessing and heads @ly015 

### Features & Enhancements

- [ ] Automate the benchmark regression @liqikai9 #849
