### ISSUE TITLE
Roadmap of MMPose

### ISSUE THREAD

**Issue by hellock** [open-mmlab/mmpose#9]
We keep this issue open to collect feature requests from users and hear your voice. Our monthly release plan is also available here.

You can either:
1. Suggest a new feature by leaving a comment.
2. Vote for a feature request with 👍 or be against with 👎. (Remember that developers are busy and cannot respond to all feature requests, so vote for your most favorable one!)
3. Tell us that you would like to help implement one of the features in the list or review the PRs. (This is the greatest things to hear about!)

**Comment by aa12356jm** [comment]
i hope that MMPose can  support  21 hand landmark detetion, thanks

**Comment by jin-s13** [comment]
> i hope that MMPose can support 21 hand landmark detetion, thanks

Good suggestions! We will add this feature in our TODO list. Thank you.

**Comment by jin-s13** [comment]
TODO List (continuously updated...):

1. Add more popular backbones & enrich the model zoo.
- [ ] ResNext
- [ ] SEResNet
- [ ] ResNetV1D
- [ ] MobileNetv2
- [ ] ShuffleNetv1

2. Add more popular datasets:
- [ ] [CrowdPose](https://github.com/Jeff-sjtu/CrowdPose)
- [ ] [MPII-TRB](https://github.com/kennymckormick/Triplet-Representation-of-human-Body)

3. Support other tasks:
- [ ] 2d hand keypoint estimation.

**Comment by gachiemchiep** [comment]
Would you mind add https://github.com/open-mmlab/mmpose/issues/31#issuecomment-663334223 to the TODO list.

**Comment by jin-s13** [comment]
> Would you mind add [#31 (comment)](https://github.com/open-mmlab/mmpose/issues/31#issuecomment-663334223) to the TODO list.

Sure.

**Comment by innerlee** [comment]
Speed up inference https://github.com/open-mmlab/mmpose/issues/40

**Comment by jin-s13** [comment]
Support video pose estimation #67

**Comment by pablovela5620** [comment]
Would be great to add support for whole body pose estimation dataset (body+face+hands) via [COCO-WholeBody](https://github.com/jin-s13/COCO-WholeBody)

**Comment by lan786** [comment]
Also add support for MPII in mmdetection.

**Comment by OasisYang** [comment]
It would be great to add support for pose tracking dataset i.e. posetrack2017/2018.

**Comment by flynnamy** [comment]
Support to convert pytorch model to onnx by the way.Thx！

**Comment by innerlee** [comment]
@OasisYang could you elaborate? is loading the data and processing on a frame basis is enough, or you want the tracking part also?

@flynnamy sounds like a request for a general tool. maybe we can provide such tools for the whole mm-series (just saying, not a confirmation).

**Comment by OasisYang** [comment]
@innerlee If possible, adding both data loading and tracking part would be great. However, the tracking part seems a little bit complicate and always comes with some extra modules. Maybe, the first step is basically to support the data loading and processing. Thanks

> @OasisYang could you elaborate? is loading the data and processing on a frame basis is enough, or you want the tracking part also?
> 
> @flynnamy sounds like a request for a general tool. maybe we can provide such tools for the whole mm-series (just saying, not a confirmation).

**Comment by jin-s13** [comment]
Support ShuffleNet V2 & MobileNet V3 backbones. #94

**Comment by pablovela5620** [comment]
Support for [InterHand2.6](https://mks0601.github.io/InterHand2.6M/)

**Comment by Witek-** [comment]
Add Yolov4 and OpenPose

**Comment by hamedcan** [comment]
Please make it possible to obtain estimated heatmaps from methods

**Comment by innerlee** [comment]
@hamedcan could you explain more about the usage? do you want a visualizer of heatmaps during training, or a visualization tool for demo, or anything else?

**Comment by SanJotter** [comment]
Bottom up for MPII dataset?

**Comment by hamedcan** [comment]
@innerlee First, I really want to thank you for the MMPose. It really helped me. I want to compare different models' performance on hard poses. So I need to be able to observe generated heatmaps. I want a visualization tool for demo.

**Comment by HuangJunJie2017** [comment]
support memonger : https://github.com/Lyken17/pytorch-memonger

**Comment by jin-s13** [comment]
Support multi-head networks #219

**Comment by flynnamy** [comment]
Please support mpii_trb demo and mpi_inf_3dhp datasets!

**Comment by yanglilian** [comment]
Support 3d hand keypoint estimation!!!!!!

**Comment by yulong314** [comment]
Support  log info when dataset is tinty,  #333

**Comment by YibinXie** [comment]
Support PyTorch AMP training, thanks. #339

**Comment by YibinXie** [comment]
Support GCN-based methods for refining top-down results.
https://arxiv.org/pdf/2003.10506v3.pdf https://github.com/lingtengqiu/OPEC-Net 
https://arxiv.org/abs/2007.10599

**Comment by pablovela5620** [comment]
Would be great to see the integration of a hyperparameter tuner like [Optuna](https://github.com/optuna/optuna)

**Comment by MaxGodTier** [comment]
A [Unity plugin](https://en.wikipedia.org/wiki/Unity_(game_engine)) would be amazing to have, using json input data and/or real-time pose estimation with a webcam and [seeing it reflected on a 3D model](https://img.youtube.com/vi/VJkKxBRpmtE/0.jpg).

**Comment by innerlee** [comment]
@MaxGodTier do you have experience in developing unity plugin? contributions are welcome :D

**Comment by MaxGodTier** [comment]
I don't, but a dirty implementation may be possible [using an existing repo](https://github.com/keel-210/OpenPose-Rig) , it reads pose data from [simple text files each representing a single frame](https://github.com/keel-210/OpenPose-Rig/blob/master/Assets/data_Doit/10.txt) , I see two solutions: **(1)** If pose_results from mmpose were translated into the same format expected from that repo, it will work out of the box without needing to change a single line of code or **(2)** edit the repo code (C#) to use mmpose rules instead of theirs.

**Comment by aa12356jm** [comment]
Quantization Aware Training for models  to  get the int8 models ,int8 models will greatly improve inference speed #359,thanks

**Comment by zgs731** [comment]
Support DetTrack and  KeyTrack.
http://arxiv.org/abs/2003.13743  &  https://arxiv.org/abs/1912.02323

**Comment by pablovela5620** [comment]
Albumentations augmetnations similar to [mmclassification](https://github.com/open-mmlab/mmclassification/blob/996d2a76412422bcfb6e2ebd486c4cff97ad49b8/mmcls/datasets/pipelines/transforms.py#L499)

**Comment by aa12356jm** [comment]
i hope that MMPose can support 3D hand landmarks detetion, thanks

**Comment by rhiver** [comment]
Does MMPose support Single Person Pose Estimation? 
Currently I found only multi-person versions are supported.

**Comment by innerlee** [comment]
@rhiver single is a case of multi

**Comment by rhiver** [comment]
> @rhiver single is a case of multi

Sort of. But multi-person version has two stages, person detection and pose estimation, which have to infer on two models. 
So this method doesn't work for realtime pose estimation in mobile devices since it takes too long on the inference. 
MobileNetV2 is good enough for simple pose estimation. But for best FPS, it's better to let it do both single person detection and pose estimation.

**Comment by flynnamy** [comment]
I see it has supported heatmap method of face datasets now. Please support regression method of face dataset!

**Comment by jin-s13** [comment]
> I see it has supported heatmap method of face datasets now. Please support regression method of face dataset!

Do you have any recommended papers/codes ?

**Comment by flynnamy** [comment]
> > I see it has supported heatmap method of face datasets now. Please support regression method of face dataset!
> 
> Do you have any recommended papers/codes ?

Yes,wingloss:https://arxiv.org/pdf/1711.06753.pdf, and GCN+softwing loss: https://arxiv.org/pdf/2006.11697.pdf

**Comment by innerlee** [comment]
Support FashionAI https://tianchi.aliyun.com/competition/entrance/231648/introduction

**Comment by CHRIBUR0309** [comment]
I want to use mmpose with the pypi package much more easily than now; such as:

`from mmpose import top_down

top_down("darkpose", "COCO_wholebody", video_path="hoge.mp4", output_json_title="hoge") # Analyze hoge.mp4 with COCO wholebody on darkpose and output the result as hoge/hoge000000000000.json, hoge/hoge000000000001.json, hoge/hoge000000000002.json, ....`

**Comment by yeshaokai** [comment]
MPII multi-person dataset for bottom-up methods is really needed!

**Comment by cavalleria** [comment]
mediapipe hand regression

**Comment by connor-john** [comment]
> Support to convert pytorch model to onnx by the way.Thx！

@flynnamy, https://github.com/ToriML/onnx2pytorch

Might be what you after

**Comment by aa12356jm** [comment]
hi ,can you add handlandmark filtering algorithm for eliminating handlandmark  jittering  in videos?  thanks

**Comment by dineshreddy91** [comment]
Adding Vehicle pose estimation to the pipe line using CarFusion dataset. Similar to Occlusion-net,  and Apollocar3D.

**Comment by simba0703** [comment]
Export to Torchscript !

**Comment by pablovela5620** [comment]
[Lite-HRNet](https://github.com/HRNet/Lite-HRNet), its already built with mmpose so including should be super simple.

**Comment by ioctl-user** [comment]
Please support Halpe data set: https://github.com/Fang-Haoshu/Halpe-FullBody

It has 3 useful points in addition to the COCO-WholeBody.

**Comment by rubeea** [comment]
Hi everyone,

I intend to create my own keypoints dataset with 3 points of interest (two endpoints and one center point). Can anyone kindly help me on how I can create annotations to be loaded into mmpose? 
Any help in this regard will be highly appreciated.
Thank you

**Comment by jin-s13** [comment]
Support 3dpw and hp3d dataset #682

**Comment by aqsc** [comment]
Do you have any plans for the mano based hand keypoints detection? Also optimization with the IK loss

**Comment by AmitMY** [comment]
Add 3D Pose Consistency Benchmark - https://github.com/open-mmlab/mmpose/issues/828

**Comment by znoland3** [comment]
Add https://github.com/mks0601/3DMPPE_POSENET_RELEASE into MMPose

**Comment by MaxMaslov** [comment]
It would be nice to add ["PoseFormer"](https://github.com/zczcwh/PoseFormer). It based on VideoPose3D, which already supported.

**Comment by ee-lynn** [comment]
It would be nice to add "CenterNet".   it is a bottom up based 2d human pose estimation method and it  groups keypoints of one person by combine regression and heatmap of keypoints which is quite different from associated embedding and affinity fields

**Comment by APeiZou** [comment]
[Blog:Next-Generation Pose Detection with MoveNet and TensorFlow.js ](https://blog.tensorflow.org/2021/05/next-generation-pose-detection-with-movenet-and-tensorflowjs.html) 这里有movenet的简单介绍，https://storage.googleapis.com/movenet/MoveNet.SinglePose%20Model%20Card.pdf

**Comment by canghaiyunfan** [comment]
Add [RLE](https://github.com/Jeff-sjtu/res-loglikelihood-regression) into MMPose

**Comment by francesco-taioli** [comment]
**Background** : 3d pose  estimation (with video generation) with a high number of people (es: [official video](https://user-images.githubusercontent.com/15977946/124654387-0fd3c500-ded1-11eb-84f6-24eeddbf4d91.mp4), minute 00:19 sec, but with a lot of people

**Result video**: the original video is put on the top-left, with the subsuquent 3d pose of the people on the right. If there are a lot of people, the final video has strange resolution (i.e 6000x400) because every people detected is on put on the same row.

**What could be improve**: split the people 3d pose visualization into multiple row

**Comment by piercus** [comment]
It would be great to have a 'score_per_joint' option in test_cfg in order to output one score per joint, instead of having only a global score for the pose, my use case is related to associative embedding

**Comment by liwenssss** [comment]
update Interhand2.6M dataset which contains MANO hand mesh parameters.......

**Comment by walsvid** [comment]
It would be nice to have Depth-Based 3D Hand Pose Estimation methods like [A2J](https://github.com/zhangboshen/A2J).

**Comment by vra** [comment]
It would be great to have SmoothNet  trained on 3DPW and AIST++ :)

**Comment by qinb** [comment]
It would be nice to add SmoothNet training code about pose estimation, hoping it could easily retrain on my own dataset.

**Comment by Joyako** [comment]
3D Human Mesh
[frankmocap](https://github.com/facebookresearch/frankmocap)

**Comment by ly015** [comment]
> 3D Human Mesh [frankmocap](https://github.com/facebookresearch/frankmocap)

Thanks for your feedback. 3D human mesh recovery is no longer supported in MMPose. We have [MMHuman3D](https://github.com/open-mmlab/mmhuman3d) for this task and you are welcome to submit an issue there about your request.

**Comment by yshMars** [comment]
It would be so helpful for better analysis if AP for each type of body joints are printed, for example 17 AP value for 17 kinds of body joints are given when inferencing a model in MS COCO body-keypoint dataset.

**Comment by levan92** [comment]
Will be really helpful to implement [MIPNet](https://github.com/rawalkhirodkar/MIPNet) into mmpose:
 - It is particularly useful to tackle data where there are crowded/highly occluded humans. Was previously the SOTA on OCHuman before ViTPose came along. Within the realms of convnets, it should still be the SOTA, and it seems like the idea is general enough to be applied to different types of backbones.

**Comment by levan92** [comment]
Also similar to #1389 request, will be nice to integrate [ViTPose](https://github.com/ViTAE-Transformer/ViTPose) into mmpose. ViTPose is already implemented in mmpose, so I expect integration to be much easier 😄

**Comment by liuzhuang13** [comment]
It would be nice to support [ConvNeXt](https://arxiv.org/abs/2201.03545) backbones. It is a very simple model that is purely convolutional. They can serve as a drop-in replacement for ResNet or Swin Transformer architectures. ImageNet-22k pretrained ConvNeXt variants are considered state-of-the-art in this regime.

Official code: https://github.com/facebookresearch/ConvNeXt
ConvNeXt was also implemented in the [mmsegmentation](https://github.com/open-mmlab/mmsegmentation#benchmark-and-model-zoo) and [mmdetection](https://github.com/open-mmlab/mmdetection) libraries.

Thanks!

**Comment by darcula1993** [comment]
It would be nice to have Poseaug augmentation pipeline for 3d pose estimation.
official code: [(https://github.com/jfzhang95/PoseAug)]

Thanks!

**Comment by AshvantSelvam** [comment]
Would like to have Tracing support for mmPose models. 
I have been able to successfully use 'torch2torchscript' under mmdeploy.apis to trace mmSegmentation Models. However, using the same on mmPose (tried on  'higherhrnet_w32_coco_512x512')  with the following mmdeploy config: '\mmdeploy\\configs\\mmpose\\pose-detection_torchscript.py' would throw the following error:


  File "c:\users\aselvam\onedrive - mathworks\documents\dl3p\pytorch_prjct\mmdetection\mmpose\mmpose\datasets\pipelines\shared_transform.py", line 176, in __call__
    meta[key_tgt] = results[key_src]

KeyError: 'flip_index'

Would really appreciate having this feature! Thanks

**Comment by qwert31639** [comment]
Can SCRFD be added to mmpose? 
https://github.com/deepinsight/insightface/tree/master/detection/scrfd

**Comment by jin-s13** [comment]
> Can SCRFD be added to mmpose? https://github.com/deepinsight/insightface/tree/master/detection/scrfd

It seems that SCRFD is for face detection. MMPose will focus on pose estimation/keypoint detection. Maybe it is more appropriate to support it in mmdet.

**Comment by BobDLA** [comment]
Are you still woking on the openpose which has list on the ROADMAP for years?

Thanks
