### ISSUE TITLE
Iteration Plan for October 2021

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mmpose#967]
This plan captures our work in October. We will support several new algorithms (including video and 3D HPE) and improve the dataset interface and benchmark tools.

### Algorithms

- [x] [Learning Temporal Pose Estimation from Sparsely-Labeled Videos](https://arxiv.org/abs/1906.04016) (NeurIPS'19) @liqikai9  #1006 
- [ ] [Coarse-to-Fine Volumetric Prediction for Single-Image 3D Human Pose](https://arxiv.org/abs/1611.07828) (CVPR'17) @zengwang430521 @ZhiYuan-REN  #868 #975
- [ ] [HRFormer](https://github.com/HRNet/HRFormer) (NeurIPS'21) @zengwang430521 
- [ ] [LSTM Pose Machines](https://arxiv.org/abs/1712.06316) (CVPR'18) @luminxu 
- [ ] [VoxelPose](https://github.com/microsoft/voxelpose-pytorch) (ECCV'20) @wusize  #999 

### Datasets

- [x] Support Halpe dataset  #925  @jin-s13 
- [x] Support evaluation on OCHuman dataset #920 @jin-s13 

### Features & Enhancements

- [x] Add inference speed benchmark @zengwang430521 
- [ ] Support TorchServe @ly015 

### Refactors

- [ ] Refactor dataset interface towards unified design @ly015 
- [ ] Refactor transforms in pipeline to support configurable input/output field name @ly015
